import React from 'react';
import { 
  CheckCircle2, 
  ArrowRight, 
  Sparkles, 
  X, 
  Award, 
  FolderSync, 
  GitFork, 
  Target, 
  BookOpen, 
  RotateCcw,
  ShieldCheck,
  Check
} from 'lucide-react';
import { useApp } from '../context/AppContext';

export const HeroFlowGuide: React.FC = () => {
  const { 
    heroStep, 
    setHeroStep, 
    heroModalOpen, 
    setHeroModalOpen, 
    switchUser, 
    setCurrentTab, 
    setSelectedCourseId,
    setSelectedAssessmentId,
    addToast 
  } = useApp();

  if (!heroModalOpen) return null;

  const steps = [
    {
      step: 1,
      title: 'Step 1: Admin Configures Role Benchmarks',
      persona: 'Super Admin (Ravi Shankar, IAS)',
      userId: 'user-admin',
      targetTab: 'roles_matrix',
      description: 'Define exact organizational competency benchmarks for "Junior Digital Governance Officer": Data Analytics (L4), Cybersecurity (L3), Digital Governance (L4), Communication (L3).',
      actionLabel: 'Go to Roles & Competency Matrix',
      icon: GitFork,
      color: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20',
    },
    {
      step: 2,
      title: 'Step 2: Learner Discovers Competency Deficit',
      persona: 'Civil Officer (Ananya Sharma)',
      userId: 'user-learner',
      targetTab: 'dashboard',
      description: 'Log in as Ananya Sharma. View her personalized readiness cockpit highlighting Data Analytics at 42% (Level 2 vs Required Level 4 = Critical 2-Level Gap).',
      actionLabel: 'Switch to Ananya & View Cockpit',
      icon: Target,
      color: 'bg-rose-500/10 text-rose-400 border-rose-500/20',
    },
    {
      step: 3,
      title: 'Step 3: Targeted Remediation Pathway',
      persona: 'Civil Officer (Ananya Sharma)',
      userId: 'user-learner',
      targetTab: 'learning_path',
      description: 'Review the personalized, ranked curriculum generated by the multi-metric evidence engine, paired with AI diagnostic plain-English reasoning.',
      actionLabel: 'View Targeted Learning Pathway',
      icon: Sparkles,
      color: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20',
    },
    {
      step: 4,
      title: 'Step 4: Course & Multi-Section Capstone',
      persona: 'Civil Officer (Ananya Sharma)',
      userId: 'user-learner',
      targetTab: 'assessments',
      description: 'Solve the 4-section Data Analytics capstone. Deterministic engine cross-checks answers against official rubrics, verifies statutory deadline, and issues micro-credentials.',
      actionLabel: 'Take Multi-Section Capstone',
      icon: BookOpen,
      color: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    },
    {
      step: 5,
      title: 'Step 5: Executive Organizational Impact',
      persona: 'Super Admin (Ravi Shankar, IAS)',
      userId: 'user-admin',
      targetTab: 'dashboard',
      description: 'Switch back to Admin view. See IT & Digital Governance readiness jump, gap distribution shrink, and verified audit log trail recorded.',
      actionLabel: 'View Admin Executive Impact',
      icon: Award,
      color: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    },
    {
      step: 6,
      title: 'Step 6: Cross-Department Knowledge Reuse',
      persona: 'Trainer / Content Creator (Dr. Sunita Iyer)',
      userId: 'user-trainer',
      targetTab: 'knowledge_hub',
      description: 'Experience the "Duplicate Detection Moment". Search/upload Data Analytics training -> System detects verified SOP -> Reuse, Adapt, or Compare.',
      actionLabel: 'Trigger Knowledge Duplicate Engine',
      icon: FolderSync,
      color: 'bg-purple-500/10 text-purple-400 border-purple-500/20',
    },
  ];

  const handleExecuteStep = (stepObj: typeof steps[0]) => {
    setHeroStep(stepObj.step);
    switchUser(stepObj.userId);
    setCurrentTab(stepObj.targetTab);

    if (stepObj.step === 4) {
      setSelectedCourseId('course-data-capstone-03');
      setSelectedAssessmentId('assess-data-post');
    }

    setHeroModalOpen(false);
  };

  const handleResetToStep1 = () => {
    setHeroStep(1);
    switchUser('user-admin');
    setCurrentTab('roles_matrix');
    addToast({
      type: 'info',
      title: 'Walkthrough Reset',
      message: 'Restarted guided walkthrough at Step 1 (Admin Benchmark Configuration).',
    });
    setHeroModalOpen(false);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 md:p-6 bg-black/80 backdrop-blur-md overflow-y-auto">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-4xl max-h-[92vh] flex flex-col shadow-2xl overflow-hidden my-auto">
        
        {/* Header - Responsive Layout */}
        <div className="p-4 sm:p-6 border-b border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-slate-950/80">
          <div>
            <div className="flex items-center gap-2 mb-1 flex-wrap">
              <span className="text-[10px] sm:text-xs font-bold uppercase px-2.5 py-0.5 rounded-full bg-orange-500/10 text-orange-400 border border-orange-500/30">
                SIH26075 Guided Walkthrough
              </span>
              <span className="text-[10px] sm:text-xs text-slate-400 font-mono">
                Current: Step {heroStep} of 6
              </span>
            </div>
            <h2 className="text-lg sm:text-xl font-bold text-white tracking-tight">
              SkillBridge End-to-End Competency Lifecycle
            </h2>
          </div>

          <div className="flex items-center gap-2 self-end sm:self-auto">
            <button
              onClick={handleResetToStep1}
              className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white text-xs font-medium flex items-center gap-1.5 transition-colors border border-slate-700"
              title="Reset walkthrough back to Step 1"
            >
              <RotateCcw className="w-3.5 h-3.5 text-orange-400" />
              <span>Reset to Step 1</span>
            </button>

            <button
              onClick={() => setHeroModalOpen(false)}
              className="p-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white transition-colors"
              aria-label="Close Walkthrough"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Steps Grid - Responsive 1 column on mobile, 2 columns on tablet/desktop */}
        <div className="flex-1 overflow-y-auto p-4 sm:p-6 grid grid-cols-1 md:grid-cols-2 gap-3 sm:gap-4">
          {steps.map((s) => {
            const Icon = s.icon;
            const isCurrent = s.step === heroStep;
            const isCompleted = s.step < heroStep;

            return (
              <div
                key={s.step}
                className={`p-4 sm:p-5 rounded-xl border transition-all flex flex-col justify-between ${
                  isCurrent
                    ? 'bg-slate-950 border-orange-500/60 shadow-lg ring-1 ring-orange-500/30'
                    : 'bg-slate-950/40 border-slate-800 hover:border-slate-700'
                }`}
              >
                <div>
                  <div className="flex items-center justify-between gap-2 mb-2 sm:mb-3">
                    <div className="flex items-center gap-2 min-w-0">
                      <div className={`w-8 h-8 rounded-lg flex items-center justify-center border shrink-0 ${s.color}`}>
                        <Icon className="w-4 h-4" />
                      </div>
                      <span className="text-xs font-mono font-bold text-slate-300 truncate">
                        {s.persona}
                      </span>
                    </div>

                    {isCompleted ? (
                      <span className="flex items-center gap-1 text-[10px] sm:text-[11px] font-mono font-semibold text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded border border-emerald-500/20 shrink-0">
                        <Check className="w-3 h-3" /> Done
                      </span>
                    ) : isCurrent ? (
                      <span className="text-[10px] sm:text-[11px] font-mono font-semibold text-orange-400 bg-orange-500/10 px-2 py-0.5 rounded border border-orange-500/20 shrink-0">
                        Active Step
                      </span>
                    ) : null}
                  </div>

                  <h3 className="text-xs sm:text-sm font-bold text-white">
                    {s.title}
                  </h3>

                  <p className="text-[11px] sm:text-xs text-slate-300 mt-1.5 sm:mt-2 leading-relaxed">
                    {s.description}
                  </p>
                </div>

                <div className="mt-3 sm:mt-4 pt-2.5 sm:pt-3 border-t border-slate-800/80">
                  <button
                    onClick={() => handleExecuteStep(s)}
                    className={`w-full py-2 px-3 rounded-lg text-xs font-semibold flex items-center justify-center gap-2 transition-all ${
                      isCurrent
                        ? 'bg-gradient-to-r from-orange-600 to-amber-600 hover:from-orange-500 hover:to-amber-500 text-white shadow-md'
                        : 'bg-slate-800 hover:bg-slate-700 text-slate-200'
                    }`}
                  >
                    <span>{s.actionLabel}</span>
                    <ArrowRight className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
            );
          })}
        </div>

        {/* Footer info bar */}
        <div className="p-3 sm:p-4 bg-slate-950 border-t border-slate-800 flex flex-col sm:flex-row items-center justify-between gap-2 text-[11px] text-slate-400">
          <div className="flex items-center gap-2">
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            <span>Simulates complete SIH workflow across Super Admin, Civil Officer, and Content Lead perspectives.</span>
          </div>
          <button
            onClick={handleResetToStep1}
            className="text-orange-400 hover:text-orange-300 font-semibold"
          >
            Restart from 1st Step &rarr;
          </button>
        </div>

      </div>
    </div>
  );
};
